const pg = require('pg')
const c = new pg.Client('postgresql://neondb_owner:npg_JfiP2jrmbs9o@ep-young-darkness-aorwi5hv-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require')

async function main() {
  await c.connect()

  // Salary record (info is a computed property, not a DB column)
  const salRes = await c.query('SELECT power, weaker, qualifying_business, status, paid_at FROM salaries WHERE user_id = 997860')
  console.log('Salary record:', salRes.rows[0])

  // Simulate getSalaryInfo
  const power = Number(salRes.rows[0].power)
  const weaker = Number(salRes.rows[0].weaker)
  const total = power + weaker
  const otherLegs = total - power

  const PERFORMANCE_INCENTIVE_CONFIG = [
    { designation: 'Starter', criteria: 200000, reward: 999 },
    { designation: 'Bronze', criteria: 500000, reward: 2499 },
    { designation: 'Silver', criteria: 1000000, reward: 5499 },
    { designation: 'Gold', criteria: 2500000, reward: 15999 },
    { designation: 'Platinum', criteria: 5000000, reward: 24999 },
    { designation: 'Emerald', criteria: 10000000, reward: 51999 },
    { designation: 'Ruby', criteria: 30000000, reward: 105999 },
  ]

  console.log(`\npower=₹${power}, weaker=₹${weaker}, total=₹${total}, otherLegs=₹${otherLegs}`)

  const descending = [...PERFORMANCE_INCENTIVE_CONFIG].sort((a, b) => b.criteria - a.criteria)
  for (const rank of descending) {
    if (total >= rank.criteria && power >= rank.criteria * 0.6 && otherLegs >= rank.criteria * 0.4) {
      console.log(`✅ Qualifies for: ${rank.designation} = ₹${rank.reward}`)
      break
    }
  }

  // Snapshot salary
  const cfgRes = await c.query("SELECT value FROM platform_configs WHERE key = 'payout_preview_2026-08'")
  const snapshot = JSON.parse(cfgRes.rows[0].value)
  const u = snapshot.users.find(u => u.userId === 997860)
  console.log(`\nSnapshot salary: ₹${u?.workingWallet?.salary}`)
  console.log(`Snapshot gross: ₹${u?.workingWallet?.grossTotal}`)

  // The snapshot salary=9999 but getSalaryInfo should return Gold=15999
  // This means the salary record was created with different power/weaker
  // than what we see now. The salary was paid at Aug 31 but may have been
  // computed earlier when team was smaller.

  // Check: was the salary created during the August income payout?
  // The income payout creates salaries at Aug 31 23:59
  // But the working wallet payout (which creates the snapshot) uses
  // the salary from the salary table, which was already created

  // Actually: the snapshot was generated by snapshotMonthlyIncomes
  // which first resolves salaries (line 246), then reads them (line 712-717)
  // So the salary SHOULD match

  // The salary record has power=15239148, weaker=1820414
  // getSalaryInfo([15239148, 1820414]):
  // total = 17059562, top = 15239148, other = 1820414
  // Check from highest:
  // Ruby: 30M total? No (17M < 30M)
  // Emerald: 10M total ✓, 6M top ✓, 4M other? No (1.8M < 4M)
  // Platinum: 5M total ✓, 3M top ✓, 2M other? No (1.8M < 2M)
  // Gold: 2.5M total ✓, 1.5M top ✓, 1M other ✓ → ₹15,999
  
  // But snapshot shows ₹9,999. That doesn't match any tier!
  // Unless the salary record was from a PREVIOUS month and wasn't updated

  // Wait - maybe the salary was created in JULY, not August
  // Check the salary created_at
  const salDetail = await c.query('SELECT created_at, paid_at, power, weaker FROM salaries WHERE user_id = 997860')
  console.log(`\nSalary created_at: ${salDetail.rows[0].created_at}`)
  console.log(`Salary paid_at: ${salDetail.rows[0].paid_at}`)

  // The snapshot salary = 9999 doesn't match getSalaryInfo([15239148, 1820414]) = 15999
  // This suggests the salary was resolved at a DIFFERENT time when power/weaker were different
  // OR the snapshot was computed separately from the salary resolution

  await c.end()
}

main().catch(e => { console.error(e); process.exit(1) })
